### ISSUE TITLE
Not all Timer block signals are working

### ISSUE THREAD

**Issue by garrowson** [sugardose/SpaceEngineers#12]
Line 1820 [https://github.com/sugardose/SpaceEngineers/blob/af775bebb8fcb8685ec5b4eb295a9dd4ae1299c5/SamsAutopilotManager2.cs#L1820](url)

is probably missing Tags: UNDOCKED, STARTED ?

SendSignals() at least checks for them (Line 2199):
[https://github.com/sugardose/SpaceEngineers/blob/af775bebb8fcb8685ec5b4eb295a9dd4ae1299c5/SamsAutopilotManager2.cs#L2199](url)

Unfortunately, uploaded script is ver2.6.7 (current: 2.11.1)

**Comment by Apps-n-Add-Ons** [comment]
This issue was fixed in 2.11.1TC1.4 along with Remote Control on a server, etc.
It appears that 'Magistrator' is no longer supporting the script and I have spoken with him about this patch.  I am not 'taking over' the script, just doing a bit of here/there to keep it going until such time he comes back.  The patch is not posted on the Workshop as it is not my script, though the patch is available at https://discord.com/channels/871428395257458728/886596166807064598/896440067671871538

**Comment by garrowson** [comment]
Can you provide a working link? The one you postet appearently doesn't point anywhere.

**Comment by Apps-n-Add-Ons** [comment]
Sorry, you first have to join my Discord - https://discord.gg/f2FmxjyPNu

BTW, there's another couple versions I've put up (one just yesterday) that cleans up other things as well, so look toward the bottom of the sam-v2-11-1-patch channel (also look to the pinned messages at the top) for updates.

**Comment by garrowson** [comment]
thx
